package ua.nure.voitenkom.SummaryTask4.service.pdf;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.FileOutputStream;
import java.util.Date;

public class PDFService implements IPDFService{

    private final String folder;
    public static final String FORMAT = "pdf";
    private static final Logger logger = LoggerFactory.getLogger(PDFService.class);
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);

    public PDFService(String folder) {
        this.folder = folder;
    }

    @Override
    public String createFileName(int userId, int checkId) {
        return "user=" + userId + " & " + "check=" + checkId;
    }

    @Override
    public String createPath(String file) {
        return folder + "/" + file + "." + FORMAT;
    }

    @Override
    public void createPdf(String path) {
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(path));
            document.open();
            addMetaData(document);
            addTitle(document);
            addContent(document);
            document.close();
            logger.debug("PDF was created");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void addMetaData(Document document) {
        document.addTitle("Check");
        document.addSubject("Check pay");
        document.addAuthor("Car Rental");
        document.addCreator("Car Rental");
    }

    private void addTitle(Document document) throws DocumentException {
        Paragraph preface = new Paragraph();
        addEmptyLine(preface, 1);
        preface.add(new Paragraph("Check", catFont));

        addEmptyLine(preface, 1);
        preface.add(new Paragraph("Report generated by: Car Rental" + ", " + new Date(),  smallBold));

        document.add(preface);
    }

    private void addContent(Document document) throws DocumentException {
        Anchor anchor = new Anchor("How to end the rental process", catFont);
        anchor.setName("How to end the rental process");
        Chapter catPart = new Chapter(new Paragraph(anchor), 1);

        Paragraph subPara = new Paragraph("Payment", subFont);
        Section subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("To rent a car you must pay this check in any bank and send us payed check photo back"));

        subPara = new Paragraph("Check", subFont);
        subCatPart = catPart.addSection(subPara);

        Paragraph paragraph = new Paragraph();
        addEmptyLine(paragraph, 5);
        subCatPart.add(paragraph);
        createTable(subCatPart);
        document.add(catPart);
    }

    private void createTable(Section subCatPart) throws BadElementException {
        PdfPTable table = new PdfPTable(3);

        PdfPCell c1 = new PdfPCell(new Phrase("Car"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Damage"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Sum"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);

        table.addCell("1.0");
        table.addCell("1.1");
        table.addCell("1.2");
        table.addCell("2.1");
        table.addCell("2.2");
        table.addCell("2.3");

        subCatPart.add(table);
    }


    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }

}
